controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#home_page:
#    path: /
#    controller: App\Controller\HomeController::index
